### ISSUE TITLE
Add new affiliated packages to the dropdown docs menu

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy-sphinx-theme#115]
aiapy and pfsspy recently gained affiliated package status but have not been added to the drop-down menu. I'm not sure about pfsspy, but aiapy would be happy to adopt the sunpy sphinx theme if it is added to the menu.

**Comment by Cadair** [comment]
![image](https://user-images.githubusercontent.com/1391051/92633375-9aa45d00-f2ca-11ea-9f58-0e752cacae5c.png)
