### ISSUE TITLE
Clicking title of package in banner always goes back to sunpy.org

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy-sphinx-theme#125]
I'm not sure what the expected behavior here should be, but when using the theme on a package that is not sunpy such that the name in the top left corner is not sunpy, clicking this link still leads back to sunpy.org. This seems confusing. If this is the expected target, I would expect it to read sunpy. If not, it should just return the docs home page for that package.

As an example, see the [aiapy docs](https://aiapy.readthedocs.io/en/stable/)

**Comment by nabobalis** [comment]
I think you can set `logo_url` in the conf.py to change that.
