### ISSUE TITLE
radiospectra docs link is broken

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy-sphinx-theme#126]
In the documentation drop down menu, the docs for radiospectra link to https://docs.sunpy.org/projects/radiospectra/ which is a dead link. There are built docs at https://radiospectra.readthedocs.io/en/latest/

**Comment by nabobalis** [comment]
That original link should still work. We need to fix that.

**Comment by wtbarnes** [comment]
Where is the redirect done? Is this in the RTD confit for radiospectra?

**Comment by nabobalis** [comment]
I actually don't know. I would have thought it's an rtd setting.

**Comment by nabobalis** [comment]
I restored the URL to https://docs.sunpy.org/projects/radiospectra/en/latest/ but without the en/latest the URL still errors.
