### ISSUE TITLE
Add an image credit for the background image

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy-sphinx-theme#147]
its a NASA SDO/AIA image

the credit could just be in the text somewhere, it doesn't have to be a watermark. The way the scaling works it probably doesn't always show the bottom corners etc.

```
Courtesy of NASA/SDO and the AIA, EVE, and HMI science teams.
```

**Comment by nabobalis** [comment]
I've been told that its a recommendation and not a requirement
