### ISSUE TITLE
RTD version switcher on mobile is fidgety 

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy-sphinx-theme#222]
### Describe the bug

I go to open it and it does nothing.
However, if I scroll my page down to the bottom first, open the sidebar, I can see the versions and then scroll down on the sidebar.

**Comment by Cadair** [comment]
@nabobalis are you still seeing weirdness here which isn't #240 ?

**Comment by nabobalis** [comment]
I think it was the same.
