### ISSUE TITLE
sphinx-hoverxref tooltips are not legible on the dark theme

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy-sphinx-theme#223]
### Describe the bug

![image](https://github.com/sunpy/sunpy-sphinx-theme/assets/1391051/4e0e77c0-7c20-4ede-96d5-e37f1455353b)

**Comment by eKeiran** [comment]
I can work on this bug! @Cadair let me know if someone hasn't already

**Comment by nabobalis** [comment]
This will(should) be fixed by https://github.com/sunpy/sunpy-sphinx-theme/pull/228
