### ISSUE TITLE
SunPy AF table is cut off on some mobile devices with portrait orientation  

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy-sphinx-theme#25]
On Chrome it was fine. 

On Firefox it was not.

**Comment by nabobalis** [comment]
Or maybe not. On Chrome it was fine.

**Comment by nabobalis** [comment]
The table is very wide, not sure there is a fix other than just to pan the page.

**Comment by Cadair** [comment]
I need to refactor that table for content after the board meeting. I was thinking we could use a modified version of the cards?

**Comment by nabobalis** [comment]
We could, create a version without an img?

**Comment by Cadair** [comment]
Yeah, of course some packages may have their own logo in the future.

**Comment by nabobalis** [comment]
What was the main issue with the table regarding the board?

**Comment by Cadair** [comment]
Just that all those packages are not technically accepted and all are "provisional"
