### ISSUE TITLE
Mobile Menu has two each hlines

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy-sphinx-theme#26]
![screenshot from 2017-08-16 18-13-11](https://user-images.githubusercontent.com/1392107/29373457-9e1b5554-82ae-11e7-8364-5ce911716910.png)

**Comment by nabobalis** [comment]
Still there on Nexus 5x and 6P on Chrome for me.

**Comment by DuyguKeskek** [comment]
I tested it on almost all mobile phones including Nexus 5x and 6P and it looks well. Can you check again ?

**Comment by Cadair** [comment]
Looks good to me on the lastest build here: http://sunpy.org/sunpy-sphinx-theme/index.html

**Comment by nabobalis** [comment]
Still seems to be there for me on Chrome if I open the Nexus 5x or 6P view in landscape.

**Comment by nabobalis** [comment]
I do not seem to this anymore.
