### ISSUE TITLE
Release with 2to3 fixes

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy-sphinx-theme#33]
PR #32 fixed compatibility issues for 2.7. But the latest release does not include this fix. This is blocking the [solarbextrapolation doc tests from passing](https://travis-ci.org/sunpy/solarbextrapolation)

**Comment by nabobalis** [comment]
Good point, I will do a release Monday/Tuesday if you do not mind waiting.

**Comment by wtbarnes** [comment]
No rush. The docs are still building on RTD so this is not super critical.

**Comment by nabobalis** [comment]
New version should now work!

**Comment by wtbarnes** [comment]
Docs build is passing on Travis. Thanks!
