### ISSUE TITLE
The Read the Docs version select box overlaps with the footer

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy-sphinx-theme#37]
![screenshot from 2017-10-19 12-23-01](https://user-images.githubusercontent.com/1391051/31768667-43b88432-b4c8-11e7-9efe-1e0001933944.png)

We should increase the bottom padding on that element so it's always above the footer.

**Comment by nabobalis** [comment]
How did you get this to happen?

**Comment by nabobalis** [comment]
I can't replicate this so I'm gonna ignore it.

**Comment by Cadair** [comment]
Looks like a small window problem from that screenshot.

**Comment by nabobalis** [comment]
I thought so too but when I tried to resize the window I couldn't get it to happen. But maybe I need to be in phone landscape.

**Comment by Cadair** [comment]
cool
