### ISSUE TITLE
Current Issues

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy-sphinx-theme#4]
Done
====
- [x] [#B] Mouse over text is cut off on the right most column of the gallery.
- [x] [#B] Dropdown menu has an extra white space between the button and the drop-down menu
- [x] [#C] The text on a blogpost sidebar is misaligned. [Here for example](https://duygukeskek.github.io/sunpy-website/posts/2016/2016-05-26-SunPy-07.html).
- [x] [#C] Center the titles or cards in the team page
- [x] [#B] Gallery titles are not centered
- [x] [#B] Some names are still slightly covered by the top bar, [here](http://sunpy.org/sunpy-sphinx-theme/api/sunpy.util.scraper.Scraper.html#scraper) for example.
- [x] [#C] Social Media buttons moved 
- [x] [#C] Cards
    - [x] Cards not centered in portat.
    - [x] Cards are one after the other in landscape modes
- [x] [#C] Gallery download buttons **either of these two**:
    - [x] side by side
    - [x] Centered in the page 
- [x] [#C] OpenGraph support will need to be checked in a live environment, variables need to be settable using html_theme_options
- [x] [#C] Card Issues:
    - [x] Mobile devices (e.g. S7 or Iphone) cards are a bit too large
    - [x] Nexus 7 (960 by 600), the images are not scaled. Happens to any mobile device in landscape. 
    - [x] Cards with a long name are two lines (Davids!). It messes up the layout. **Only on Chrome**
- [x] [#B] search box is cut off. It seems to be too large
- [x] [#C] Sidebar looks fuzzy on the ipad pro
- [x] [#C] 1024 x 768 is now cut off
- [x] [#B] Theme needs to be checked for responsiveness as any screen types as possible.  
    - [x] Most mobile devices (using Chrome inbuilt viewer) need textsize changes, the text is really small
- [x] [#B] Dropdown support like astropy has here: http://www.astropy.org/
- [x] [#B]  ```<p class="doc-title">SunPy 0.8dev</p>```needs to be settable by the version of the docs we build. 
- [x] [#C] Bottom bar which has some kind of info like this: © 2017, SunPy  Creative Commons License Last updated on 23 Jun 2017. Created using Sphinx 1.5.4 (only not on the sunpy.org homepage). This would be generated automatically at build. 
- [X] [#B] Issues with CSS downscaling to 900-1000 pixels
- [x] [#A] Top bar link for the documentation does not work
- [x] [#A++] **the search box only works on the home page (it seems that generated/gallery/ or code_ref/ are added to the search url for the gallery or APi pages when you try to search)**
- [x] [#C] Sidebar on blog posts changes if you hover over
- [x] [#C] Sidebar added to the search results page
- [x] [#C] Comment colour kind of blends into the background.
- [x] [#B] Card CSS should be added to this. 
- [x] [#B] Sunpy logo added to the top bar or above the side bar. Probably dont need both. 
- [x] [#C] top bar to be increased in height but a little bit
- [x] [#C] sidebar might have a line of extra colour like [this has](http://dkist.cadair.com/datamodel/)
- [x] [#B] Shrink some of the white space around headers  [here](http://sunpy.org/sunpy-sphinx-theme/dev.html#modules) for example
- [x] [#B] References seem a bit off here: http://sunpy.org/sunpy-sphinx-theme/code_ref/instr/goes.html#functions
- [x] [#B] Remove the box around inline code links
- [x] [#C] Doc string colour change to #006600 for a test, the top string is the doc string [here](http://sunpy.org/sunpy-sphinx-theme/dev.html#modules)
- [x] [#C] String colour mismatch? [Here](http://sunpy.org/sunpy-sphinx-theme/api/sunpy.util.scraper.Scraper.html#sunpy.util.scraper.Scraper)
- [x] [#C] Sidebar scrolls horizontally  where we have long names that are cutoff on the sidebar.
- [x] [#B] Sidebar scrolls horizontally (still happens on chrome for me, not in firefox)
- [x] [#C] Long names are cutoff on the sidebar
- [x] [#C] Grey outline in sidebar for subitems
- [x] [#A] It is not very clear what level links are at in the sidebar, some sort of indicator or highlight
- [x] [#A] the sidebar feels a little to cramped when you are in subpages
- [x] [#A] the toctree depth should be higher and themed
- [x] [#A] There is the anchor links go behind the nav bar bug
- [x] [#B] Long side bar has issues with scrolling
    - [x] [#B] ideally made to be scrollable like RTD sidebar is. 
    - [x] [#B] scrolls to the bottom when you first scroll down, like RTD is.
- [x] [#B] the headings in the methods documentation sections are not as clear as in the RTD theme
- [x] [#B] the syntax highlighting default is not as good as the RTD theme
- [x] [#B] the table for the api docs [like this](http://sunpy.org/sunpy-sphinx-theme/code_ref/time.html) needs better styling.
- [x] [#B] there should be a "SunPy Documentation" heading at the top of the side bar, currently says version of the docs.
- [x] [#B] some combo of border, background and padding is needed around each function name
- [x] [#C] font size on the code heading blocks is too large and there are font size variations 
- [x] [#C] the space as function name and the . needs to be lessened 
- [x] [#C] Fix the sidebar scrolling jump bug

**Comment by Cadair** [comment]
the never ending list of things part II:

- [ ] the toctree depth should be higher and themed
- [ ] the search box only works on the home page
- [ ] the table for the api docs [like this](http://sunpy.org/sunpy-sphinx-theme/code_ref/time.html) needs better styling.
