### ISSUE TITLE
Mouseover Highlight Issue

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy-sphinx-theme#43]
Sidebar before:
![screenshot from 2018-02-16 11-55-50](https://user-images.githubusercontent.com/1392107/36304609-8653b612-1310-11e8-9358-472f997d303f.png)

Sidebar after mouseover:
![screenshot from 2018-02-16 11-55-56](https://user-images.githubusercontent.com/1392107/36304612-886fb518-1310-11e8-9beb-7ed13a77ec6a.png)

**Comment by nabobalis** [comment]
Chrome only.

**Comment by Cadair** [comment]
Its probably because the text gets too wide for the sidebar on mouseover. No idea on why it only happens in chrome.

**Comment by nabobalis** [comment]
It just seems to happen for that item

**Comment by Cadair** [comment]
Is that because it's the longest in letters? The others probably change size but not enough to make it line wrap

**Comment by nabobalis** [comment]
Looks like there is some padding-left that isn't applied consistently. But only affects chrome which is odd.

**Comment by nabobalis** [comment]
JUST INCREASE FONT SIZE TO 18 #SOrTED
