### ISSUE TITLE
There is now an extra footer dot

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy-sphinx-theme#78]
![image](https://user-images.githubusercontent.com/1391051/56119289-be436680-5f63-11e9-89ef-4bae453ba9e8.png)

**Comment by nabobalis** [comment]
That is intentional.

**Comment by nabobalis** [comment]
Made it easier to loop over the list and add the dots than to worry about some sort of if statement.

**Comment by Cadair** [comment]
We should special case it, it looks a bit crap :stuck_out_tongue:

**Comment by nabobalis** [comment]
I kind of like it on extra side tho.

**Comment by nabobalis** [comment]
But I'll work out a workaround.

**Comment by Cadair** [comment]
I am sure I have seen a thing in Jinja where you can do different things with first/last loops

**Comment by nabobalis** [comment]
{% if forloop.first %} would probably work.
