### ISSUE TITLE
Support RTD this version is not the latest box

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy-sphinx-theme#84]
It shows pre-sunpy theme https://docs.sunpy.org/en/v0.7.9/ but not post-sunpy theme https://docs.sunpy.org/en/v0.8.5/index.html

**Comment by nabobalis** [comment]
RTD calls out to some javascript to check if the theme is rtd_like.

That function checks:

```javascript
return 1 === $("div.rst-other-versions").length || (this.theme === r.THEME_RTD || this.theme === r.THEME_MKDOCS_RTD)
```

We need to replicate the first argument (hopefully) to make RTD think our theme is like that.

**Comment by nabobalis** [comment]
See: https://github.com/rtfd/readthedocs.org/blob/4450ec6df1b623d1b2bc7c31ba98e9e502ee5bf5/readthedocs/core/static-src/core/js/doc-embed/rtd-data.js

**Comment by nabobalis** [comment]
Already the case it seems.
