### ISSUE TITLE
Opening page does not show lower buttons

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy-sphinx-theme#9]
Chrome Version 59.0.3071.115 (Official Build) (64-bit)
Apple MacBook Pro (Retina, 13-inch, Early 2015) OSX, 10.10.5

<img width="1276" alt="screen shot 2017-08-02 at 1 43 27 pm" src="https://user-images.githubusercontent.com/983575/28886876-017b990a-7789-11e7-8e79-eac7f39588a8.png">

**Comment by nabobalis** [comment]
@wafels Can you try again now? We moved the elements of the front page around.

**Comment by wafels** [comment]
On the same machine:
<img width="1279" alt="screen shot 2017-08-07 at 9 07 04 am" src="https://user-images.githubusercontent.com/983575/29027733-f1d84e4c-7b4f-11e7-8c76-167c46b4bb09.png">

**Comment by nabobalis** [comment]
@wafels We added some more items to the front page, do they all show up for you?

**Comment by wafels** [comment]
It showed up on my non-Retina Mac, using Firefox 54.0.1
