### ISSUE TITLE
Automatically re-trigger RTD on release

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy-sphinx-theme#97]
We have a lot of projects which use the sphinx theme and if the top bar or other global things change all these need rebuilding.

We should be able to do this using the rtd api https://docs.readthedocs.io/en/stable/api/v3.html#build-triggering

**Comment by nabobalis** [comment]
Fixed by https://github.com/sunpy/sunpy-sphinx-theme/pull/98
